version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    environment:
      - cluster.name=goomba-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    networks:
      - stack

  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.3
    environment:
      - xpack.security.enabled=false
      - xpack.grokdebugger.enabled=false
      - xpack.graph.enabled=false
      - xpack.ml.enabled=false
      - xpack.reporting.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.monitoring.ui.container.elasticsearch.enabled=false
    ports:
      - 5601:5601
    depends_on: 
      - elasticsearch
    networks:
      - stack

networks:
  stack:
    driver: bridge
